config/routes.rb
Babelmail::Application.routes.draw do
  resources :babels

  resources :contacts

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users

  authenticated :user do
    root to: "contacts#index", as: :authenticated_root
  end

  unauthenticated :user do
    root to: "home#index"
  end

  get 'users/select_plan' => 'pricing#select_plan'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/babel.rb
class Babel < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base

	validates_format_of :firstname, :with => /([a-z]|[A-Z])/, presence: true
	validates_format_of :lastname, :with => /([a-z]|[A-Z])/, presence: true
	validates_uniqueness_of :email, scope: [:user], presence: true
	validates :language, presence: true

	belongs_to :user

	before_save :set_hash

  def set_hash 

  	self.firstname = self.firstname.split(/(\W)/).map(&:capitalize).join
  	self.lastname = self.lastname.split(/(\W)/).map(&:capitalize).join

  	@trybabel = self.firstname + self.lastname + "." + self.user.username + "@babel-mail.com"

  	@trybabel = @trybabel.delete(' ').downcase

  	@counter = Contact.where(babeladdress: @trybabel).count.to_s

  	if @counter != "0"

  		@trybabel = self.firstname + self.lastname + @counter + "." + self.user.username + "@babel-mail.com"

  		@trybabel = @trybabel.delete(' ').downcase

  	end

  	self.babeladdress = @trybabel

  end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  before_create :add_credit

  validates :username, format: { with: /\A[0-9a-zA-Z]+\z/,
   										 message: "only allows letters and numbers" }, 
   										 presence: true, 
   										 uniqueness: true

  validates :account_type, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :contacts

  def add_credit

  	self.credits = 5

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name << :surname << :username << :account_type
    devise_parameter_sanitizer.for(:account_update) << :name << :surname << :username << :account_type
  end

	def confirm_logged_in
	    unless session[:id]
	        flash[:notice] = "Please log in"
	        redirect_to :root
	        return false
	    else
	        return true
	    end
	end

  
end

app/controllers/babels_controller.rb
class BabelsController < ApplicationController
  before_action :set_babel, only: [:show, :edit, :update, :destroy]

  # GET /babels
  # GET /babels.json
  def index
    @babels = Babel.all
  end

  # GET /babels/1
  # GET /babels/1.json
  def show
  end

  # GET /babels/new
  def new
    @babel = Babel.new
  end

  # GET /babels/1/edit
  def edit
  end

  # POST /babels
  # POST /babels.json
  def create
    @babel = Babel.new(babel_params)

    respond_to do |format|
      if @babel.save
        format.html { redirect_to @babel, notice: 'Babel was successfully created.' }
        format.json { render action: 'show', status: :created, location: @babel }
      else
        format.html { render action: 'new' }
        format.json { render json: @babel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /babels/1
  # PATCH/PUT /babels/1.json
  def update
    respond_to do |format|
      if @babel.update(babel_params)
        format.html { redirect_to @babel, notice: 'Babel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @babel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /babels/1
  # DELETE /babels/1.json
  def destroy
    @babel.destroy
    respond_to do |format|
      format.html { redirect_to babels_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_babel
      @babel = Babel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def babel_params
      params.require(:babel).permit(:message)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = current_user.contacts
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = current_user.contacts.new
  end

  # GET /contacts/1/edit
  def edit
    @contact = current_user.contacts.find(params[:id])
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = current_user.contacts.new(contact_params)

    respond_to do |format|
      if @contact.save
        @contacts = current_user.contacts
        format.html { redirect_to contacts_url, notice: 'Contact was successfully added.' }
      else
        format.html { render action: 'new' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    @contact = current_user.contacts.find(params[:id])

    respond_to do |format|
      if @contact.update(contact_params)
        @contacts = current_user.contacts
        format.html { redirect_to contacts_url, notice: 'Contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact = current_user.contacts.find(params[:id])

    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:firstname, :lastname, :email, :language, :babeladdress)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pricing_controller.rb
class PricingController < ApplicationController

	before_filter :confirm_logged_in, :only => [:show]

  def select
  	
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_filter :authenticate_user!

  def pricing
    @user = User.find(params[:id])
    # If this show page is only for the currently logged in user change it to @user = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/babels_helper.rb
module BabelsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/babels/_form.html.erb
<%= simple_form_for(@babel) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :message %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/babels/edit.html.erb
<h1>Editing babel</h1>

<%= render 'form' %>

<%= link_to 'Show', @babel %> |
<%= link_to 'Back', babels_path %>

app/views/babels/index.html.erb
<h1>Listing babels</h1>

<form action="/charge" method="POST">
  <script
    src="https://checkout.stripe.com/checkout.js"
    class="stripe-button"
    data-key="pk_test_6pRNASCoBOKtIshFeQd4XMUh"
    data-image="/square-image.png"
    data-name="Demo Site"
    data-description="2 widgets ($20.00)"
    data-amount="2000">
  </script>
</form>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @babels.each do |babel| %>
      <tr>
        <td><%= babel.message %></td>
        <td><%= link_to 'Show', babel %></td>
        <td><%= link_to 'Edit', edit_babel_path(babel) %></td>
        <td><%= link_to 'Destroy', babel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Babel', new_babel_path %>

app/views/babels/new.html.erb
<h1>New babel</h1>

<%= render 'form' %>

<%= link_to 'Back', babels_path %>

app/views/babels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @babel.message %>
</p>

<%= link_to 'Edit', edit_babel_path(@babel) %> |
<%= link_to 'Back', babels_path %>

app/views/contacts/_form.html.erb
<%= simple_form_for(@contact) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class="col-md-6">
      <%= f.input :firstname, :label => "First name"  %>
    </div>
    <div class="col-md-6">
      <%= f.input :lastname, :label => "Last name" %>
    </div>
    <div class="col-md-12">
      <%= f.input :email %>
      <%= f.label :language %> <br>
      <%= f.select(:language, options_for_select([['Chinese', 'Chinese'], ['Japanese', 'Japanese'], ['Korean', 'Korean'], ['Spanish', 'Spanish'], ['French', 'French'], ['German', 'German']], 2)) %>
      <div class="form-actions">
        <%= f.button :submit, :class => "btn btn-success" %>

      </div>
    </div>

  </div>

  
<% end %>

app/views/contacts/edit.html.erb
<div class="form-page">
	<div class="container">
		<div class="row">
			<div class="col-md-6 col-md-offset-3">
	  	
	  		<h2>Update Babel Contact</h2>
				<h5></h5>
		  
  			<div class="form-box">

					<%= render 'form' %>

					<center><%= link_to 'Cancel', contacts_path %></center>

				</div>
			</div>
		</div>
	</div>
</div>

app/views/contacts/index.html.erb
<div class="normal-page">
<div class="container">
  <div class="pop-up">

<div class="well">
  <div class="row">
    
      <div class="col-md-12"><span>Your Babel Address is <span class="flatgreen" data-intro="This is your <span class='flatgreen'>Babel Address</span>, created just for you. <br><br>When you send an email through Babel Mail during the free trial, your contacts will receive and reply emails from this address"><%= current_user.username.downcase %>@babel-mail.com</span></span></div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12"><span class="normal-page-title">Contacts</span></div>
  </div>

  <div class="row"><div class="col-md-12">
    <div class="table-responsive">
      <table class="table" data-step="2" data-intro="These are your <span class='flatgreen'>Babel Contacts</span>. Add as many as you'd like!">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Send emails to</th>
            <th>Language</th>
            <th></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @contacts.each do |contact| %>
            <tr>
              <td><%= contact.firstname %> <%= contact.lastname %></td>
              <td><%= contact.email %></td>
              <td><%= mail_to contact.babeladdress do %>
                <% contact.babeladdress %>
                <% end %>
              </td>
              <td><%= contact.language %></td>
              <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
              <td><%= link_to 'Delete', contact, method: :delete, data: { confirm: 'Are you sure?' }, :class => "flatred" %></td>
            </tr>
          <% end %>
            <tr>
              <td>Andrew Babel</td>
              <td>andrew.h.jiang@gmail.com</td>
              <td data-step="3" data-intro="To write an email to Andrew, send your email to his unique <span class='flatgreen'>Babel Address</span> created just for you">
                <a href="mailto:andrew.<%= current_user.username.downcase %>@babel-mail.com">
                andrew.<%= current_user.username.downcase %>@babel-mail.com
                </a>
              </td>
              <td data-step="4" data-intro="Andrew will receive your email translated in <span class='flatorange'>Chinese</span>, and his replies will get back to you in <span class='flatorange'>English</span>">Chinese</td>
              <td><%= content_tag(:span, 'Edit',  :class => "lightgray") %></td>
              <td><%= content_tag(:span, 'Delete',  :class => "lightgray") %></td>
            </tr>
          <tr>
              <td data-step="5" data-intro="It's that simple! <br><br>Get started by adding a new contact, and start connecting with the world"><%= link_to '+ New Contact', new_contact_path %></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
            </tr>
        </tbody>
      </table>
    </div>
  </div>

<!-- Modal -->
<div class="modal fade" id="welcome-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title" id="welcome-modal-label">Welcome to Babel Mail!</h3>
      </div>
      <div class="modal-body introjs-tooltiptext">
        To get you started, follow along the tutorial and learn how to send and receive translated emails directly from your email client (e.g. Gmail, Outlook, Yahoo)
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" id="start-tutorial" autofocus>Start Tutorial!</button>
        <button type="button" class="btn" data-dismiss="modal">No thanks</button>
      </div>
    </div>
  </div>
</div>

  </div></div>
</div>
</div>

app/views/contacts/new.html.erb
<div class="form-page">
	<div class="container">
		<div class="row">
			<div class="col-md-6 col-md-offset-3">
	  	
	  		<h2>Add Babel Contact</h2>
				<h5></h5>
		  
  			<div class="form-box">

					<%= render 'form' %>

					<center><%= link_to 'Cancel', contacts_path %></center>

				</div>
			</div>
		</div>
	</div>
</div>

app/views/contacts/show.html.erb
<div class="normal-page">
	<div class="container">
	  <div class="pop-up">
			<div class="well">
	  		<div class="row">

					<p id="notice"><%= notice %></p>

					<p>
					  <strong>Firstname:</strong>
					  <%= @contact.firstname %>
					</p>

					<p>
					  <strong>Lastname:</strong>
					  <%= @contact.lastname %>
					</p>

					<p>
					  <strong>Email:</strong>
					  <%= @contact.email %>
					</p>

					<p>
					  <strong>Language:</strong>
					  <%= @contact.language %>
					</p>

					<%= link_to 'Edit', edit_contact_path(@contact) %> |
					<%= link_to 'Back', contacts_path %>

				</div>
			</div>
		</div>
	</div>
</div>

app/views/home/index.html.erb
<script>
    mixpanel.track("Landing page loaded");
    $('#key-features-link').attr('href', '#key-features');
    $('#languages-and-pricing-link').attr('href', '#languages-and-pricing')
</script>
<div class="container-fluid divider-inside-top-bottom">
  <div class="mask-container">
    <div id="landing-image">
      <div class="container">
        <div class="row">
          <div class="col-md-6" id="landing-hero">
            <span class="hero-type">Send human-translated emails instantly</span>
            <span class="hero-type"><h3>Write in your language and Babel Mail directly translates both emails you send and receive </h3></span>
            <br><br>
            <%= link_to new_user_registration_path, class: "btn btn-lg  button-default" do %>
              <span>Get 5 Translations FREE</span>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div id="key-features">
    <div class="container">
      <div class="row marketing-row">
        <h1>How it works</h1>
        <div class="col-md-4 marketing-block">
          <center><span class="glyphicon glyphicon-envelope marketing-icon"><span class="marketing-icon-num">1</span></span></center>
          <p>Write in your language</p>
          Add your foreign language contacts to Babel Mail, then compose and send emails as you normally would
        </div>
        <div class="col-md-4 marketing-block">
          <center><span class="glyphicon glyphicon-user marketing-icon"><span class="marketing-icon-num">2</span></span></center>
          <p>Human + machine translation</p>
          After an intitial machine translation, our skilled translators edit and deliver the perfect translation to your contact
        </div>
        <div class="col-md-4 marketing-block">
          <center><span class="glyphicon glyphicon-send marketing-icon"><span class="marketing-icon-num">3</span></span></center>
          <p>Receive translated replies</p>
          Inbound replies get translated as well, so you'll feel like you're communicating entirely in your own language!
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div id="languages-and-pricing">
    <div class="container">
      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <h1>Six major languages. One simple price.</h1>
          <div>
            <table class="table">
              <tr>
                <td><%= image_tag "flags/China.png", class: "flag-small" %><span><strong>Chinese</span></td>
                <td><%= image_tag "flags/Japan.png", class: "flag-small" %><span>Japanese</span></td>
                <td><%= image_tag "flags/South_Korea.png", class: "flag-small" %><span>Korean</span></td>
              </tr>
              <tr class="coming-soon">
                <td><%= image_tag "flags/Spain.png", class: "flag-small" %><span>Spanish</span></td>
                <td><%= image_tag "flags/France.png", class: "flag-small" %><span>French</span></td>
                <td><%= image_tag "flags/Germany.png", class: "flag-small" %><span>German</span></td>
              </tr>
            </table>
          </div>
          <div class="box-well">Only 2¢ per Word
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div id="large-visual">
    <div class="container">
      <div class="row email-visual">
        <h1>Just write and send.</h1>
        <h3>We do all the rest</h3>
        <div class="col-md-5 email-visual-sender">
          <div class="email-visual-title">
            <div class="row">
              <div class="col-md-12">
                Sent to: <strong>Andrew (江汉琪)</strong>
              </div>
              <div class="col-md-12">
                Subject: <strong>Hi from California!</strong>
              </div>            
            </div>
          </div>
          <div class="email-visual-body">
            Hi Andrew! How are you doing? We missed you at the holiday party this year. 
            When are you coming for a visit?
            <br><br>
            Sincerely,<br>
            John

          </div>
        </div>
        <div class="col-md-2 arrow">
          <span class="glyphicon glyphicon-chevron-right"></span>
          <%= image_tag "babel-small.png", class: "fish-visual-right"%>
        </div>
        <div class="col-md-5 email-visual-recipient">
          <div class="email-visual-title">
            <div class="row">
              <div class="col-md-12">
                Received by: <strong>Andrew (江汉琪)</strong>
              </div>
              <div class="col-md-12">
                Subject: <strong>你好从加州</strong>
              </div>
              
            </div>
          </div>
          <div class="email-visual-body">
            江先生, 你好吗？我们错过了你在圣诞派对。你什么时候会来看看我们？
            <br><br>
            恭祝,<br>
            John
          </div>
        </div>
      </div>
      <div class="row">
        <div class="down-arrow left">
          <span class="glyphicon glyphicon-chevron-down"></span>
        </div>
      </div>
      <div class="row email-visual received">
        <div class="col-md-5 email-visual-sender">
          <div class="email-visual-title">
            <div class="row">
              <div class="col-md-12">
                Received by: <strong>John</strong>
              </div>
              <div class="col-md-12">
                Subject: <strong>RE:Hi from California!</strong>
              </div>
              
            </div>
          </div>
          <div class="email-visual-body">
            John, it is a pleasure to hear from you. I am doing very well and planning on visiting the San Francisco office next month.
            <br><br>
            Best,<br>
            Andrew
          </div>
        </div>
        <div class="col-md-2 arrow">
          <%= image_tag "babel-small.png", class: "fish-visual-left"%>
          <span class="glyphicon glyphicon-chevron-left"></span>
        </div>
        <div class="col-md-5 email-visual-recipient">
          <div class="email-visual-title">
            <div class="row">
              <div class="col-md-12">
                Sent to: <strong>John</strong>
              </div>
              <div class="col-md-12">
                Subject: <strong>RE:你好从加州</strong>
              </div>
              
            </div>
          </div>
          <div class="email-visual-body">
            John, 我很高兴收到你的来信。我很好。下个月，我打算参观旧金山办事处。
            <br><br>
            恭祝,<br>
            江汉琪
          </div>
        </div>
      </div>
      <div class="row">
        <div class="down-arrow right">
          <span class="glyphicon glyphicon-chevron-down"></span>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid" id="try-it-free">
  <div id="apply-today">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <center>
            <%= link_to new_user_registration_path, class: "btn btn-lg button-default" do %>
              <span>Try it FREE</span>
            <% end %>
          <center>
          <br>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer divider-inside-top">
  <div class="container" id="footer">
    <div class="row">
      <div class="col-md-6" id="footerLeft">
        © 2014 Babel Mail - Connect with the World
      </div>
      <div class="col-md-6" id="footerRight">
        Contact Us &nbsp;&nbsp; | &nbsp;&nbsp;<a href="mailto:hello@babel-mail.com" >hello@babel-mail.com</a>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header babel-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#babel-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand babel-brand" href="/"><%= image_tag "babel-small.png", class: "babel-brand-img" %> Babel Mail</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->

    <% if user_signed_in? %>
      <%= render 'layouts/navbar_signed_in' %>
    <% else %>
      <%= render 'layouts/navbar_signed_out' %>
    <% end %>
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navbar_signed_in.html.erb
<div class="collapse navbar-collapse" id="babel-navbar-collapse">
      <ul class="nav navbar-nav pull-right">
        <li id="header-msg">
        	Hi
				  <%= link_to edit_user_registration_path, :id => "header-name" do %> 
				  <%= current_user.username %><% end %>, you have <%= content_tag(:span, :class => "flatgreen") do %> <%= current_user.credits %> free email(s) <% end %> left
				</li>
				<li>
				  <%= link_to destroy_user_session_path, :method => :delete, class: "dropdown-toggle CTA", id: "header-signout" do %>
				    Log out
				  <% end %>
				  <ul class="dropdown-menu signed-out pull-right" role="menu">
				  </ul> 
				</li>
      </ul>
      <div class="hidden" id="sign-in-count">
      	<%= current_user.sign_in_count %>
      </div>
      <div class="hidden" id="contacts-count">
      	<%= current_user.contacts.count %>
      </div>
    </div><!-- /.navbar-collapse -->

app/views/layouts/_navbar_signed_out.html.erb
<div class="collapse navbar-collapse" id="babel-navbar-collapse">
  <ul class="nav navbar-nav" id="babel-main-links">
    <li><a class= "scroll-link" href="/#key-features" id="key-features-link">How it works</a></li>
    <li><a class= "scroll-link" href="/#languages-and-pricing" id="languages-and-pricing-link">Languages & Pricing</a></li>
  </ul>
  <ul class="nav navbar-nav pull-right">
		<li>
		  <%= link_to("Sign up", new_user_registration_path, id: "header-CTA") %>
		</li>
		<li>
			<%= link_to new_user_session_path, class: "CTA", id: "header-signin" do %>
			Login
			<% end %>
		  <ul class="dropdown-menu signed-out pull-right" role="menu">
		  </ul> 
		</li>
	</ul>
</div><!-- /.navbar-collapse -->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/pricing/select_plan.html.erb
<div class="form-page">
<div class="container">
  <div class="row"><div class="col-md-10 col-md-offset-1">

  <h2>Choose your account type</h2>
  <h5>No credit card needed until your 5 FREE trial translations are used</h5>

  	<div class="row" id="pricing-table">

  		<div id="pricePlans">
				<ul id="plans">
					<li class="plan">
						<ul class="planContainer">
							<li class="title"><h2>Trial</h2></li>
							<li class="price"><p>FREE</p></li>
							<li>
								<ul class="options">
									<li>5 <span>emails free</span></li>
									<li>2 hour <span>turnaround</span></li>
									<li>Chinese <span>only</span></li>
									<li>Unlimited <span>contacts</span></li>
									<li>Business hours <span>support</span></li>
								</ul>
							</li>
							<li class="button"><a href="#">Select</a></li>
						</ul>
					</li>

					<li class="plan">
						<ul class="planContainer">
							<li class="title"><h2 class="bestPlanTitle">Standard</h2></li>
							<li class="price"><p class="bestPlanPrice">$20/month</p></li>
							<li>
								<ul class="options">
									<li>10 <span>emails per month</span></li>
									<li>1 hour <span>turnaround</span></li>
									<li>All languages</li>
									<li>Unlimited <span>contacts</span></li>
									<li>24 hour <span>support</span></li>
								</ul>
							</li>
							<li class="button"><a class="bestPlanButton" href="#">Select</a></li>
						</ul>
					</li>

					<li class="plan">
						<ul class="planContainer">
							<li class="title"><h2>Power</h2></li>
							<li class="price"><p>$50/<span>month</span></p></li>
							<li>
								<ul class="options">
									<li>25 + 5 EXTRA <span>emails per month</span></li>
									<li>30 minute <span>turnaround</span></li>
									<li>All languages</li>
									<li>Unlimited <span>contacts</span></li>
									<li>24 hour <span>support</span></li>
								</ul>
							</li>
							<li class="button"><a href="#">Select</a></li>
						</ul>
					</li>

				</ul> <!-- End ul#plans -->
			</div>

  	</div>

  
  </div></div>
</div>
</div>